pipeline:
  notify:
    image: plugins/downstream
    server: https://bianca.toroid.io
    repositories:
      - Toroid-io/drone-kicad
    when:
      event: push
      status: success
      branch: master
